### ISSUE TITLE
add default project health files

### ISSUE THREAD

**Issue by skuethe** [cloudeteer/.github#1]
See github documentation:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types

- `CONTRIBUTING.md`
- `SUPPORT.md`
- `SECURITY.md`
- (possibly) `CODE_OF_CONDUCT.md`

**Comment by geraldfehringer** [comment]
Please, use sample foundation here: https://github.com/cloudeteer/runbooks/blob/main/SECURITY.md
